### ISSUE TITLE
Качаю проект пытаюсь собрать через F5 получаю ошибки 

### ISSUE THREAD

**Issue by cibermax** [Tinkoff/invest-api-csharp-sdk#10]
![image](https://user-images.githubusercontent.com/7147503/158085700-fa986414-4034-40f1-b87f-b33a7380fa69.png)
подскажите чего не хватает

**Comment by rus-art** [comment]
Что выводит, если собирать через командную строку `dotnet build`?

**Comment by Oblomoff** [comment]
Папка investAPI пустая. Ни одного *.proto файла.

**Comment by rus-art** [comment]
Да, надо клонировать через git clone --recurse-submodules

**Comment by kitMP** [comment]
Распишите подробно, что нужно сделать. Где эти протофайлы, где дать эту команду git clone --recurse-submodules ? У меня в консоли выдаётся ошибка по этой команде.

**Comment by rus-art** [comment]
Мы находимся в github, тут используется система управления версиями git. Когда вы хотите скачать себе исходники любого проекта на github, вам надо клонировать себе репозиторий.

Ссылку для клонирования можно увидеть взять тут

![image](https://user-images.githubusercontent.com/18074929/190569206-c334bb9e-f890-4351-ad8f-b1ae29c03802.png)

То есть переходим в папку на компьютере, куда хотим получить исходники, открываем терминал и вводим команду. 

```
git clone --recurse-submodules https://github.com/Tinkoff/invest-api-csharp-sdk.git
```

До этого нужно установить git себе на компьютер.

После того, как репозиторий склонирован, можно открывать sln файл и собирать

Как использовать git - большая тема, рекомендую ознакомиться с документацией, например, [тут](https://git-scm.com/book/ru/v2)

**Comment by rus-art** [comment]
Обновил README, раздел [Сборка из исходников](https://github.com/Tinkoff/invest-api-csharp-sdk/blob/main/README.md#%D1%81%D0%B1%D0%BE%D1%80%D0%BA%D0%B0-%D0%B8%D0%B7-%D0%B8%D1%81%D1%85%D0%BE%D0%B4%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2)

**Comment by kitMP** [comment]
Я сторонник минимализма, не нравится устанавливать доп. софт на ПК, если им редко пользуюсь. Поэтому сделал клонирование репозитория непосредственно из MSVS и нужные пакеты появились, после чего проект собрался.

**Comment by rus-art** [comment]
Если получилось клонировать через MSVS, значит git уже стоит

**Comment by kitMP** [comment]
Ничего из git точно не установлено.
