### ISSUE TITLE
Есть возможность использовать одновременно 2 токена?

### ISSUE THREAD

**Issue by OdCheban** [Tinkoff/invest-api-csharp-sdk#13]
services.AddInvestApiClient(...) - каждый вызов этой команды переписывает значение заново? Так же хотелось что бы работа происходила в одном контексте;

**Comment by rus-art** [comment]
Да, это поддерживается. Используется механизм [именованных клиентов] (https://docs.microsoft.com/en-us/aspnet/core/grpc/clientfactory?view=aspnetcore-6.0#named-clients)

**Comment by OdCheban** [comment]
> Да, это поддерживается. Используется механизм [именованных клиентов](https://docs.microsoft.com/en-us/aspnet/core/grpc/clientfactory?view=aspnetcore-6.0#named-clients)

gRPC только начал изучать, если возможно - добавьте пожалуйста пример;

**Comment by OdCheban** [comment]
gRPC только начал изучать, если возможно - добавьте пожалуйста пример;
@rus-art

**Comment by OdCheban** [comment]
var builder = Host.CreateDefaultBuilder(args);
var host = builder.ConfigureServices((context, services) =>
    {
        services.AddHostedService<AsyncSample>();
        services.AddInvestApiClient("one", (_, settings) => settings.AccessToken = "___");
        services.AddInvestApiClient("two", (_, settings) => settings.AccessToken = "___");
    }).Build();
await host.RunAsync();
        

public class AsyncSample : BackgroundService
{
    private readonly List<InvestApiClient> clients = new List<InvestApiClient>();
    private readonly IHostApplicationLifetime _lifetime;
    private readonly ILogger<AsyncSample> _logger;

    public AsyncSample(ILogger<AsyncSample> logger, GrpcClientFactory grpcClientFactory, IHostApplicationLifetime lifetime)
    {
        _logger = logger;
        clients.Add(grpcClientFactory.CreateClient<InvestApiClient>("one"));
        clients.Add(grpcClientFactory.CreateClient<InvestApiClient>("two"));
        _lifetime = lifetime;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        foreach (var client in clients)
        {
            var accounts = await client.Users.GetAccountsAsync();
            foreach (var account in accounts.Accounts)
                Console.WriteLine(account.Id + " " + account.AccessLevel);
        }
        _lifetime.StopApplication();
    }
}
