### ISSUE TITLE
В репозитории отсутсвует ряд файлов, проект не компилируется!

### ISSUE THREAD

**Issue by Cold-Rain** [Tinkoff/invest-api-csharp-sdk#14]
В репозитории отсутсвует ряд файлов, проект не компилируется!
В частности нет таких сервисов как MarketDataService, MarketDataStreamService, OperationsService, OrdersService, OrdersStreamService, SandboxService, StopOrdersService и связанных с ними обьектов.

**Comment by rus-art** [comment]
Добрый день. Эти классы генерируются через Source generators напрямую из .proto файлов. Эти файлы в свою очередь лежат в подмодуле, который надо тоже клонировать
Используйте `git clone --recurse-submodules`

**Comment by kitMP** [comment]
Ничего непонятно, где это надо использовать...

**Comment by rus-art** [comment]
Как скачиваете исходники себе на компьютер?

**Comment by kitMP** [comment]
Download zip
![image](https://user-images.githubusercontent.com/62998882/190576245-20499aa1-780e-4049-b22f-e4d74a143703.png)
