### ISSUE TITLE
Есть ли способ интерактивного взаимодействия с либой?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [Tinkoff/invest-api-csharp-sdk#17]
Я так понимаю, все тут заточено под сервисы и т. д. Очень хотелось бы, чтобы можно было из юпитер ноутбука со своим портфелем играться. Планируется ли такое API? 

В старом API свой портфель можно было получить тремя строчками:
```cs
var connection = ConnectionFactory.GetConnection(token);
var context = connection.Context;
var portfolio = await context.PortfolioAsync();
```
но теперь оно выдает ошибку `Tinkoff.Trading.OpenApi.Network.OpenApiException: Unauthorized: You have no access to that resource..`, я так понимаю, это апи закрыли. А в новом такой красоты я не нашел, если я, конечно, все правильно понимаю.

**Comment by vabka** [comment]
Вы можете попробовать  в интерактивном режиме поиграться при помощи .NET Interactive Notebooks
https://github.com/dotnet/interactive
Есть и расширение для VS Code, и кернелы для Jupyter

Чтобы начать использовать, достаточно написать вот такой код в первой ячейке:

```cs
#r "nuget: Microsoft.Extensions.DependencyInjection, 6.0.0"
#r "nuget: Microsoft.Extensions.DependencyInjection.Abstractions, 6.0.0"
#r "nuget: Tinkoff.InvestApi, 0.1.6"


using Microsoft.Extensions.DependencyInjection;
using Tinkoff.InvestApi;
using Tinkoff.InvestApi.V1;

var token = "ТУТ ТОКЕН";

var serviceCollection = new ServiceCollection();
serviceCollection.AddInvestApiClient((_, settings) =>
{
    settings.AccessToken = token;
});
var serviceProvider = serviceCollection.BuildServiceProvider();
var client = serviceProvider.GetRequiredService<InvestApiClient>();

var accountsRequest = new GetAccountsRequest {};
var accountsResponse = await client.Users.GetAccountsAsync(accountsRequest);

var portfolioRequest = new PortfolioRequest{
    AccountId = accountsResponse.Accounts[0].Id
};
var portfolioResponse = await client.Operations.GetPortfolioAsync(portfolioRequest);

portfolioResponse.Positions.Display();
```

**Comment by WhiteBlackGoose** [comment]
Спасибо!
