### ISSUE TITLE
Отсутствие поля CurrentNkd в классе Bond

### ISSUE THREAD

**Issue by OdCheban** [Tinkoff/invest-api-csharp-sdk#18]
В классе PortfolioPosition имеется переменная .CurrentNkd;
В классе Bond переменная отсутствует;

Это неправильно и переменную .CurrentNkd нужно целиком перенести в класс Bond т.к. класс PortfolioPosition относится ко всем активам при этом НКД у акций нет.

**Comment by vabka** [comment]
Bond - это облигация сама по себе. А НКД может быть только у позиции портфеля.

`PortfolioPosition` представляет из себя любую позицию портфеля, и отличить в нём акцию от облигации можно по свойству `InstrumentType`
У акции оно будет равно `share`, у облигации - `bond`, а у валют - `currency`

**Comment by OdCheban** [comment]
> Bond - это облигация сама по себе. А НКД может быть только у позиции портфеля.
> 
> `PortfolioPosition` представляет из себя любую позицию портфеля, и отличить в нём акцию от облигации можно по свойству `InstrumentType` У акции оно будет равно `share`, у облигации - `bond`, а у валют - `currency`

тогда стоит просто переименовать переменную. У акции не может быть нкд

**Comment by vabka** [comment]
Возможно, я не совсем понимаю.

У акций же это поле вообще null должно быть или чем-то подобным.

**Comment by OdCheban** [comment]
> Возможно, я не совсем понимаю.
> 
> У акций же это поле вообще null должно быть или чем-то подобным.

У акций этого поля вообще не должно быть - я вот о чем. Но впрочем вопрос был задан слишком давно, поэтому вопрос закроем
