### ISSUE TITLE
А можно увидеть хоть какой-нибудь работающий пример?

### ISSUE THREAD

**Issue by AndreyVolodin2** [Tinkoff/invest-api-csharp-sdk#20]
Кажется единственная цель этого SDK - чтобы никто никогда и нечего не смог написать на этом API. Человек с начальными знаниями в C# просто идет н@Х... мимо. Что у вас в разделе "быстрый старт"? Это что такое? Какой, нахрен, Services? как с ним работать? Вы издеваетесь что-ли? UserSecrets - отдельный изощренный способ послать пользователя на 3 буквы. Я все понимаю - не правильно хранить токен в тексте кода, но, простите, во-первых это не вам решать, во вторых, я только что на openApi хранил его в коде, и до сих пор жив, а в третьих, дайте же хоть какой-нибудь пример, для запуска которого не нужно штудировать отвлеченные темы в программировании.

Просто windows forms программу. Вида: Токен сюда, эта кнопка выводит в консоль список инструментов, эта кнопка выводит текущую цену такого-то figi, эта кнопка создает заявку на покупку, эта на продажу. Я слишком многого прошу?

**Comment by cibermax** [comment]
Полностью согласен и поддерживаю данный вопрос

**Comment by rus-art** [comment]
Появился [новый пример](https://github.com/Tinkoff/invest-api-csharp-sdk/tree/main/Examples/Tinkoff.InvestApi.Examples.MarketDataStream), посмотрите, покрывает ли он ваш вопрос по быстрому старту.

Так же хочу напомнить что проект open source, это значит что любой человек может внести свой вклад. Текущий код написан волонтерами бесплатно, без предоставления гарантий. Ваше негодование понятно. Но проект появился недавно, и мы работаем все вместе друг для друга. Предлагаю внести вклад и поработать над стартовой страницей, улучшить ее.

**Comment by AndreyVolodin2** [comment]
@rus-art Да?.. Это странно. Там написано, что это официальный C# SDK. В чем заключается его официальность, если он написан энтузиастами, а не сотрудниками Тинькофф банка?

**Comment by rus-art** [comment]
Да, энтузиастами, сотрудниками Тинькофф и не сотрудниками Тинькофф. Тем не менее лицензия не дает никаких гарантий, за эту библиотеку никто никому не заплатил. Это обычный open source. Лучше не хейтить, а помочь.
