### ISSUE TITLE
Кто-нибудь может поделиться примером?

### ISSUE THREAD

**Issue by AndreyVolodin2** [Tinkoff/invest-api-csharp-sdk#22]
Я ничего не понимаю в этом SDK. Все эти "подробные описания" лично мне ничего не описывают. Он вообще работает? Хоть кому-нибудь удалось на C# что-нибудь получить от серверов Тинькофф? Поделитесь, пожалуйста примером, который работает. Спасибо.

**Comment by rus-art** [comment]
Попробуйте [новый пример](https://github.com/Tinkoff/invest-api-csharp-sdk/tree/main/Examples/Tinkoff.InvestApi.Examples.MarketDataStream). В дальнейшем будем работать над упрощением примеров для вашего комфорта
