### ISSUE TITLE
Просьба добавить получение данных из объекта(не сервиса) как это реализовано в текущем java sdk и как примерно было в старом c# sdk

### ISSUE THREAD

**Issue by BlankaKorvo** [Tinkoff/invest-api-csharp-sdk#26]
Привет!
Спасибо за уже проделанную работу!
Есть несколько просьб/замечаний)

- В старом шарповом SDK, была удобная возможность получать торговые данные без прибивания себя гвоздями ~~к потолку за яйца~~ на сервисы ASP. 
На соседнем актуальном https://github.com/Tinkoff/invest-api-java-sdk это уже даже изобрели.

Пример из старого SDK:
```
using Tinkoff.Trading.OpenApi.Network;
...
// токен аутентификации
var token = "my.token";
// для работы в песочнице используйте GetSandboxConnection
var connection = ConnectionFactory.GetConnection(token);
var context = connection.Context;

// вся работа происходит асинхронно через объект контекста
var portfolio = await context.PortfolioAsync();
```

Просьба вернуть конструктивно схожий функционал.

- Так же, хочется иметь возможность подписываться на обновления по инструментам. 
Пример ожидаемой семантики:
```
var marketClient= new MarketClient(Figi, бла, бла, бла);
marketClient.Events.Orderbook += myHandler;
marketClient.Start();
Ну или что то в этом духе.
```
- Молоток, долото и пассатижи описанные в https://github.com/Tinkoff/invest-api-csharp-sdk/blob/main/CONTRIBUTING.md - это все конечно весело и интересно, но как Вы и сами можете догадаться не очень удобно. Особенно, когда планируешь пользоваться готовым NuGet...
Просьба автоматизировать обновление/синхронизацию версий с базовым сабмодулем.
Спасибо огромное!
С нетерпением жду позитивных изменений!

**Comment by rus-art** [comment]
Спасибо за фидбек! Тут много всего, по сути два предложения и один вопрос, поэтому завел отдельные задачи #28 #29.

От ServiceCollection отказаться не можем, так как сам grpc клиент так настраивается. Но можем эту логику скрыть под коврик. 

Подписаться сейчас можно, [есть новый пример](https://github.com/Tinkoff/invest-api-csharp-sdk/blob/main/Examples/Tinkoff.InvestApi.Examples.MarketDataStream/Program.cs#L21-L41). Правда не так просто, как было раньше, тоже из-за grpc.

Так же хочу напомнить что проект open source, хоть и большинство волонтеров из Tinkoff. Поэтому будем рады любой помощи и улучшениям. Спасибо за инициативу!
