### ISSUE TITLE
C# ругается на PostOrderRequest.Price - не могу создать запрос на операцию.

### ISSUE THREAD

**Issue by AndreyVolodin2** [Tinkoff/invest-api-csharp-sdk#27]
var client2 = new Tinkoff.InvestApi.V1.SandboxService.SandboxServiceClient(chanel);

PostOrderRequest r = new PostOrderRequest();

            r.Figi = "BBG0047315Y7";
            r.OrderId = "1";
            r.Price.Units = 1185;
            r.Price.Nano = 0;
            r.Direction = OrderDirection.Buy;
            r.OrderType = OrderType.Limit;

            var rep = client2.PostSandboxOrder(r , headers);

Ругается на строку r.Price.Units = 1185; говорит Object reference not set! Как это исправить?

**Comment by TVlZh** [comment]
` r.Price = new Quotation { Nano = 0, Units = 1185 }; `
Так как Price является объектом, то его нужно сначала инициализировать как объект, а потом заполнить значения полей.

**Comment by AndreyVolodin2** [comment]
@TVlZh Добрый человек, а подскажите, как этот самый Quotation можно в итоге конвертнуть в какой-нибудь Double или что-то подобное? Хочу например понять, была ли растущей последняя свеча и на какой процент, а у меня только этот странный тип, который не сложит и не вычесть.

**Comment by AlexanderVolkovTCS** [comment]
>конвертнуть в какой-нибудь Double

Value = Units  + Nano / 1,000,000,000
