### ISSUE TITLE
Пример MarketDataStream не работает

### ISSUE THREAD

**Issue by AlexanderKryukov** [Tinkoff/invest-api-csharp-sdk#31]
Пытаюсь понять как работать со стримами. 
Запускаю пример приведенный здесь:
https://github.com/Tinkoff/invest-api-csharp-sdk/tree/main/Examples/Tinkoff.InvestApi.Examples.MarketDataStream
получаю один ответ:
{"SubscribeCandlesResponse":{"TrackingId":"62fe93e1c85ebbbb2fd31637ab7a5a8d","CandlesSubscriptions":[{"Figi":"BBG004730N88","Interval":1,"SubscriptionStatus":3}]},"SubscribeOrderBookResponse":null,"SubscribeTradesResponse":null,"SubscribeInfoResponse":null,"Candle":null,"Trade":null,"Orderbook":null,"TradingStatus":null,"Ping":null,"SubscribeLastPriceResponse":null,"LastPrice":null,"PayloadCase":1}
и больше ничего не происходит.

Подскажите пожалуйста, в чем проблема?

**Comment by rus-art** [comment]
Биржа работала в это время?

**Comment by AlexanderKryukov** [comment]
Да работала, сейчас проверяю, тоже самое.
Еще иногда приходит ответ:
{"SubscribeCandlesResponse":null,"SubscribeOrderBookResponse":null,"SubscribeTradesResponse":null,"SubscribeInfoResponse":null,"Candle":null,"Trade":null,"Orderbook":null,"TradingStatus":null,"Ping":{"Time":{"Seconds":1660903480,"Nanos":878161866}},"SubscribeLastPriceResponse":null,"LastPrice":null,"PayloadCase":9}
и потом опять тишина

**Comment by vabka** [comment]
Когда я писал этот пример, тоже с этим сталкивался.

Но я тестировал только в то время, когда биржа уже не работала.

**Comment by vabka** [comment]
Похоже, этот PR должен чинить: https://github.com/Tinkoff/invest-api-csharp-sdk/pull/32

**Comment by rus-art** [comment]
Подтвердите, пожалуйста, исправлена ли ошибка?

**Comment by somescout** [comment]
У меня так и не работает подписка на Order book - все остальные вроде корректно возвращают данные, а orderbook - только пинги. При этом запрос через просто 
```
client.MarketData.GetOrderBook(new GetOrderBookRequest
{
    Figi = "BBG004730JJ5",
    Depth = 8
});
```
отрабатывает нормально.

**Comment by AlexanderKryukov** [comment]
Сейчас все работает, спасибо!
