### ISSUE TITLE
ResourceExhausted при получении всѣх брендов

### ISSUE THREAD

**Issue by OZ1** [Tinkoff/invest-api-csharp-sdk#34]
Выполнение запроса `.Instruments.GetBrands(new()).Brands` безусловно завершается с _Grpc.Core.RpcException: "Status(StatusCode="ResourceExhausted", Detail="Received message exceeds the maximum configured message size.")"_

**Comment by OZ1** [comment]
{
  "code": 8,
  "message": null,
  "description": "gRPC message exceeds maximum size 4194304: 5522388"
}

**Comment by rus-art** [comment]
Должно поправиться в 0.1.8
