### ISSUE TITLE
Версия релиза.

### ISSUE THREAD

**Issue by kitMP** [Tinkoff/invest-api-csharp-sdk#41]
Поясните по версиям. Сейчас на git-е официальная последняя  версия:
![image](https://user-images.githubusercontent.com/62998882/196378218-ac077aec-4b09-4897-83cd-7a50444de4b4.png)
В основном репозитории:
![image](https://user-images.githubusercontent.com/62998882/196378405-382ba811-8415-4cf9-af9c-032158ee58ac.png)
При этом по версии csharp-а я не нашёл каких либо описаний последних изменений. И как версия csharp соотносится с версией в основном репозитории?
Также необходимо указать версию на странице в поле Releases:
![image](https://user-images.githubusercontent.com/62998882/196379128-1b3a628b-40e7-456f-9dac-19e5d44bf6ad.png)

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, версия обновлена.

**Comment by rus-art** [comment]
Версия SDK никак не соотносится с версией InvestApi. Есть предложения как этот момент понятнее сделать? Ведь релиз может содержать изменения независимые от обновления InvestApi

**Comment by kitMP** [comment]
Можно на странице SDK  рядом со словом Latest указывать, какая версия основного API используется в релизе. Например, 0.3.0 Latest (V1.0.14) или так 0.3.0 (V1.0.14) Latest. Или хотя бы в описании нового релиза всегда указывать, какая версия InvestaAPi используется.  Например, такой вариант мне понятен:
![image](https://user-images.githubusercontent.com/62998882/198832033-4df05adb-b428-4919-8b89-7b9846cca86f.png)
Если обновления контрактов нет, можно просто писать используемую версию контрактов.

**Comment by rus-art** [comment]
Согласен, будем так делать
