### ISSUE TITLE
Не устанавливается цена исполнения стоп-ордера

### ISSUE THREAD

**Issue by informa-ru** [Tinkoff/invest-api-csharp-sdk#44]
`tp=90;
PostStopOrderRequest postStopOrderRequest = new PostStopOrderRequest();
postStopOrderRequest.AccountId = accountID;
postStopOrderRequest.Direction = StopOrderDirection.Sell;
postStopOrderRequest.Figi = pos.Figi;
postStopOrderRequest.Quantity = (long)ConvertQuotationToDecimal(pos.QuantityLots);
postStopOrderRequest.StopOrderType = StopOrderType.TakeProfit;
postStopOrderRequest.ExpirationType = StopOrderExpirationType.GoodTillDate;
postStopOrderRequest.ExpireDate = DateTime.SpecifyKind(DateTime.Now.AddDays(stopOrdersLifeTime), DateTimeKind.Utc).ToTimestamp();
Quotation p = new Quotation();
p.Units = (long)Math.Truncate((decimal)tp);
p.Nano = (int)Math.Truncate(1000000000 * ((decimal)tp - p.Units));
postStopOrderRequest.Price = p;
postStopOrderRequest.StopPrice = p;
client.StopOrders.PostStopOrder(postStopOrderRequest);`
Цена активации = 99, цена исполнения = 0, несмотря на указанное значение postStopOrderRequest.Price

**Comment by b1ng0o** [comment]
Добрый день, не могли бы прислать stopOrderId, или если проблема повторяется то  x-tracking-id свежего запроса

**Comment by AlexanderVolkovTCS** [comment]
Если проблема актуальна, прошу переоткрыть тикет.
