### ISSUE TITLE
Не получается получить историю по минутным свечам. Работает только часовые и дневные

### ISSUE THREAD

**Issue by BlankaKorvo** [Tinkoff/invest-api-csharp-sdk#45]
Добрый день.
Быстрый старт в консоли:
`            InvestApiClient client = InvestApiClientFactory.Create(token);
            GetCandlesRequest getCandlesRequest = new GetCandlesRequest() { Figi = figi, From = Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-6)), Interval = Tinkoff.InvestApi.V1.CandleInterval.Hour, To = Timestamp.FromDateTime(DateTime.UtcNow) };
            var result = client.MarketData.GetCandles(getCandlesRequest);`
Выполняется успешно.
Однако если выбрать минутные интервалы, то происходит ошибка: "Grpc.Core.RpcException: "Status(StatusCode="InvalidArgument", Detail="30014")""
К примеру: 
`            InvestApiClient client = InvestApiClientFactory.Create(token);
            GetCandlesRequest getCandlesRequest = new GetCandlesRequest() { Figi = figi, From = Timestamp.FromDateTime(DateTime.UtcNow.AddDays(-6)), Interval = Tinkoff.InvestApi.V1.CandleInterval._5Min, To = Timestamp.FromDateTime(DateTime.UtcNow) };
            var result = client.MarketData.GetCandles(getCandlesRequest);`

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, 
Максимально запрашиваемый интервал для часового таймфрейма - неделя (https://tinkoff.github.io/investAPI/load_history/)
А для минутного - всего сутки.

Рекомендуем либо разбить запрашиваемый период на меньшие интервалы, либо воспользоваться сервисов загрузкок архивных минутных котировок: https://tinkoff.github.io/investAPI/get_history/
