### ISSUE TITLE
Получить количество доступных позиций

### ISSUE THREAD

**Issue by OdCheban** [Tinkoff/invest-api-csharp-sdk#47]
![image](https://user-images.githubusercontent.com/29703030/208609875-6cf6bebf-520f-4bb1-a565-f1aa0355ca50.png)
Как получить колонку "Доступно" через API?

**Comment by AlexanderVolkovTCS** [comment]
В методе [GetPositions](https://tinkoff.github.io/investAPI/operations/#getpositions) возвращается количество доступных и заблокированных позиций.
