### ISSUE TITLE
Подключение к Sandbox endpoint

### ISSUE THREAD

**Issue by somescout** [Tinkoff/invest-api-csharp-sdk#48]
В настройках клиента нет возможности указать адрес endpoint'а и, соответственно, нет возможности нормально работать с песочницей. Можно ли добавить в конфигурацию AddInvestApiClient возможность указать адрес endpoint'а?

**Comment by rus-art** [comment]
Добавил опцию для работы с песочницей

```
InvestApiClientFactory.Create(accessToken, sandbox: true);
```

или

```
InvestApiClientFactory.Create(new InvestApiSettings { AccessToken = accessToken, Sandbox = true });
```
