### ISSUE TITLE
Не причины ошибки при выставлении поручения в песочнице

### ISSUE THREAD

**Issue by sergey2048** [Tinkoff/invest-api-csharp-sdk#50]
Не причины ошибки при выставлении поручения в песочнице
Пример торгового поручения

03/09/2023 18:06:01 +03:00 - 
MRKY: BBG000C7P5M7 - 
ордер Limit цена за лот -  412,5. Лотов: 48. Цена текущая: 0.0417. lotSize: 10000 priceStep: 0.00005. Результат - ошибка.  Status(StatusCode="FailedPrecondition", Detail="90001") 

Т.е. почему-при торговле всеми инструментами, цена которых меньше единицы я получаю ошибку 90001 (требуется подтверждение операции). 
При этом подробностей, как обещает документация api в тексте ошибке нет. Просто текст : 
Detail="90001

**Comment by AlexanderVolkovTCS** [comment]
При выставлении ордера свыше 6 млн руб. подтверждение заявки - обязательно. 

Список ошибок доступен по ссылке https://tinkoff.github.io/investAPI/errors/
