### ISSUE TITLE
PortfolioStream

### ISSUE THREAD

**Issue by imzharikov** [Tinkoff/invest-api-csharp-sdk#51]
Господа а сабж вообще рабочий?) При попытке использовать возвращает {{ "accounts": [ { "accountId": "**********", "subscriptionStatus": "PORTFOLIO_SUBSCRIPTION_STATUS_SUCCESS" } ] }} , и при этом null в свойствах Ping и Portfolio

**Comment by AlexanderVolkovTCS** [comment]
Да. В этом стриме события отправляются по факту любого изменения портфеля. Между изменениями отправляется сообщение ping в целях поддержания соединения.
